### ISSUE TITLE
Subtraction with overflow in autohinting

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#1218] opened 2024-11-04 14:17 UTC
Repro: https://github.com/drott/fontations/commit/6bf4d82948842f3b4dacb6a3163724c79d3a6ea0

Spun off from:
https://issues.chromium.org/374808876

```
   3: skrifa::outline::autohint::latin::blues::compute_default_blues
             at ./src/outline/autohint/latin/blues.rs:187:28
   4: skrifa::outline::autohint::latin::blues::compute_unscaled_blues
             at ./src/outline/autohint/latin/blues.rs:37:13
   5: skrifa::outline::autohint::latin::metrics::compute_unscaled_style_metrics
             at ./src/outline/autohint/latin/metrics.rs:51:28
   6: skrifa::outline::autohint::metrics::UnscaledStyleMetricsSet::get
             at ./src/outline/autohint/metrics.rs:151:21
   7: skrifa::outline::autohint::instance::Instance::draw
             at ./src/outline/autohint/instance.rs:109:23
   8: skrifa::outline::hint::HintingInstance::draw
             at ./src/outline/hint.rs:413:17
```

Font in commit uploaded for testing purposes, must not be used verbatim as a test case.

**Comment by dfrg** [comment] 2024-11-04 15:33
Per IM, this overflow is caused by a subtraction of contour indices before doing a comparison with the contour length. In this case, we're performing the operation `0 - 22` which overflows since we're using unsigned numbers. FreeType uses signed arithmetic here, avoiding the overflow but also allowing this bounds check condition to succeed.

Rasterizing the glyph from this test case in FreeType doesn't seem to produce any artifacts and the hinting appears to be reasonable.

Autohinted:
![Image](https://github.com/user-attachments/assets/da7af73f-0d02-4cae-9120-a882b9108247)

Unhinted:
![Image](https://github.com/user-attachments/assets/a46700f1-1fd2-4b90-9ddf-089ebb37f5da)

Given this, I think we should just match FT's behavior, using a signed comparison for these indices.

**Comment by dfrg** [comment] 2024-11-04 15:57
Suggested fix at #1219. Constructing a test case for this without using the offending font will take some time which I don't have at the moment.

**Comment by rsheeter** [comment] 2024-11-04 16:56
We can leave this issue open to track adding a test. We don't have to block landing the fix but lets not go too long without the test either.

**Comment by dfrg** [comment] 2024-11-11 13:48
Ended up adding a minimal test case in #1219 so closing this issue.

**Closed by dfrg** 2024-11-11 13:48 UTC
